<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class CandidateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $usersData = [
            [
                'name' => 'Minn Thu Ta',
                'email' => 'minnthuta606@gmail.com',
                'password' => bcrypt('thutaminn999'),
                'img' => 'tt.jpg',
                'cover' => '1.jpg',
                'bio' => 'Passionate software engineer with a love for problem-solving and a knack for creating efficient and scalable solutions. Always eager to stay ahead in the ever-evolving tech landscape',
                'position' => 'Web Developer',
                'birthday' => '2003-05-02',
                'age' => 20,
                'phone' => '09943985243',
                'country' => 'Myanmar',
                'city' => 'Yangon',
                'skills' => '["1","2","3","4","5","6"]',
                'preferred_category' => 10,
                'experience' => '2 Years',
                'min_salary' => 500,
                'max_salary' => 2000,
            ],
            [
                'name' => 'Mikel Erwin Nusa',
                'email' => 'erwinnusa@gmail.com',
                'password' => bcrypt('erwinnusa'),
                'img' => '04.jpg',
                'cover' => '2.jpg',
                'bio' => 'DevOps enthusiast with a strong background in automating processes and optimizing infrastructure. Continuously seeking ways to enhance deployment pipelines for seamless software delivery.',
                'position' => 'System Audit',
                'birthday' => '1991-01-23',
                'age' => 33,
                'phone' => '09943985243',
                'country' => 'United States',
                'city' => 'New York',
                'skills' => '["19","18","17","2","10","12"]',
                'preferred_category' => 5,
                'experience' => '10 Years',
                'min_salary' => 1500,
                'max_salary' => 3000,
            ],
            [
                'name' => 'Christopher Nolan',
                'email' => 'chrisnolan@gmail.com',
                'password' => bcrypt('chrisnolan'),
                'img' => '01.jpg',
                'cover' => '1.jpg',
                'bio' => 'Detail-oriented quality assurance engineer with a passion for ensuring software reliability and user satisfaction. Proficient in manual and automated testing methodologies.',
                'position' => 'Quality Assurance Engineer',
                'birthday' => '1987-12-02',
                'age' => 37,
                'phone' => '09943985243',
                'country' => 'United States',
                'city' => 'New York',
                'skills' => '["9","3","6","2","10","12"]',
                'preferred_category' => 5,
                'experience' => '10 Years',
                'min_salary' => 1500,
                'max_salary' => 3000,
            ],
            [
                'name' => 'Mimi Keeni',
                'email' => 'mimi@gmail.com',
                'password' => bcrypt('mimikeeni'),
                'img' => '05.jpg',
                'cover' => '3.jpg',
                'bio' => 'Full-stack developer blending creativity with technical expertise. Specializing in building user-centric applications that marry functionality with a polished user interface.',
                'position' => 'System Audit',
                'birthday' => '1999-4-25',
                'age' => 37,
                'phone' => '09942474613',
                'country' => 'United States',
                'city' => 'New York',
                'skills' => '["20","21","1","6","10","12"]',
                'preferred_category' => 10,
                'experience' => '3 Years',
                'min_salary' => 1000,
                'max_salary' => 1500,
            ],
            [
                'name' => 'Justin Alba',
                'email' => 'justinalba@gmail.com',
                'password' => bcrypt('justinalba'),
                'img' => '02.jpg',
                'cover' => '3.jpg',
                'bio' => 'Data scientist with a passion for uncovering insights from complex datasets. Proficient in machine learning and statistical analysis, dedicated to transforming raw data into actionable business intelligence.',
                'position' => 'Data Scientist',
                'birthday' => '1987-12-02',
                'age' => 37,
                'phone' => '09973658253',
                'country' => 'United States',
                'city' => 'New York',
                'skills' => '["12","3","15","17","20","10"]',
                'preferred_category' => 1,
                'experience' => '12 Years',
                'min_salary' => 1800,
                'max_salary' => 3000,
            ],
            [
                'name' => 'Hsu Mon',
                'email' => 'hsumon@gmail.com',
                'password' => bcrypt('hsumon'),
                'img' => '05.jpg',
                'cover' => '1.jpg',
                'bio' => 'Experienced IT project manager skilled in orchestrating cross-functional teams and delivering high-impact projects on time and within budget. Adept at mitigating risks and ensuring stakeholder satisfaction.',
                'position' => 'Project Manager',
                'birthday' => '2004-07-12',
                'age' => 19,
                'phone' => '09420930238',
                'country' => 'Myanmar',
                'city' => 'Yangon',
                'skills' => '["5","1","16","18","6","21"]',
                'preferred_category' => 2,
                'experience' => '1 Year',
                'min_salary' => 1000,
                'max_salary' => 1200,
            ],
            [
                'name' => 'Sergio Besto',
                'email' => 'besto@gmail.com',
                'password' => bcrypt('sergiobesto'),
                'img' => '06.jpg',
                'cover' => '2.jpg',
                'bio' => 'Cybersecurity specialist committed to safeguarding digital assets and implementing robust security measures. Skilled in penetration testing, threat analysis, and incident response.',
                'position' => 'Cybersecurity Specialist',
                'birthday' => '1987-12-02',
                'age' => 37,
                'phone' => '09943985243',
                'country' => 'United States',
                'city' => 'New York',
                'skills' => '["9","3","6","2","10","12"]',
                'preferred_category' => 5,
                'experience' => '10 Years',
                'min_salary' => 1500,
                'max_salary' => 3000,
            ],
            [
                'name' => 'Florian Swift',
                'email' => 'florianswift@gmail.com',
                'password' => bcrypt('florianswift'),
                'img' => '04.jpg',
                'cover' => '3.jpg',
                'bio' => 'Cloud architect with a focus on designing and implementing scalable, secure, and cost-effective cloud solutions. Expertise in AWS, Azure, and Google Cloud Platform.',
                'position' => 'Frontend Engineer',
                'birthday' => '1995-12-5',
                'age' => 29,
                'phone' => '09654368712',
                'country' => 'United States',
                'city' => 'New York',
                'skills' => '["9","3","6","2","10","12"]',
                'preferred_category' => 5,
                'experience' => '10 Years',
                'min_salary' => 1500,
                'max_salary' => 3000,
            ],
            [
                'name' => 'Musa Momiji',
                'email' => 'momiji@gmail.com',
                'password' => bcrypt('momiji'),
                'img' => 'ok.jpg',
                'cover' => '1.jpg',
                'bio' => 'Network engineer with a passion for optimizing network performance and ensuring seamless connectivity. Experienced in designing, implementing, and managing enterprise-level networks.',
                'position' => 'Network Engineer',
                'birthday' => '1999-10-18',
                'age' => 24,
                'phone' => '09623971467',
                'country' => 'Japan',
                'city' => 'Nagoya',
                'skills' => '["9","3","6","2","10","12"]',
                'preferred_category' => 5,
                'experience' => '5 Years',
                'min_salary' => 1000,
                'max_salary' => 1200,
            ],
            [
                'name' => 'Sashimi',
                'email' => 'sashimi@gmail.com',
                'password' => bcrypt('sashimi'),
                'img' => '04.jpg',
                'cover' => '3.jpg',
                'bio' => 'UI/UX designer with a keen eye for aesthetics and a user-centered design approach. Proficient in creating intuitive and visually appealing interfaces that enhance the overall user experience',
                'position' => 'UI/UX designer',
                'birthday' => '2001-03-12',
                'age' => 23,
                'phone' => '09943985243',
                'country' => 'Japan',
                'city' => 'Nagoya',
                'skills' => '["20","21","6","2","10","12"]',
                'preferred_category' => 7,
                'experience' => '5 Years',
                'min_salary' => 800,
                'max_salary' => 1200,
            ],
            [
                'name' => 'Justin Dash',
                'email' => 'justindash@gmail.com',
                'password' => bcrypt('justindash'),
                'img' => '07.jpg',
                'cover' => '2.jpg',
                'bio' => 'System administrator with a knack for optimizing server performance and ensuring the reliability of IT infrastructure. Experienced in managing Linux and Windows environments.',
                'position' => 'System administrator',
                'birthday' => '1993-08-31',
                'age' => 31,
                'phone' => '0923158112',
                'country' => 'United States',
                'city' => 'New York',
                'skills' => '["4","5","6","2","10","20"]',
                'preferred_category' => 8,
                'experience' => '10 Years',
                'min_salary' => 3500,
                'max_salary' => 5000,
            ],
            [
                'name' => 'Harry Maguire',
                'email' => 'harrymaguire@gmail.com',
                'password' => bcrypt('harrymaguire'),
                'img' => '08.jpg',
                'cover' => '2.jpg',
                'bio' => 'IT consultant with a diverse skill set encompassing systems integration, IT strategy, and project management. Committed to driving digital transformation for clients.',
                'position' => 'IT consultant',
                'birthday' => '1985-12-02',
                'age' => 39,
                'phone' => '09943985243',
                'country' => 'United States',
                'city' => 'New York',
                'skills' => '["10","8","6","2","10","12"]',
                'preferred_category' => 2,
                'experience' => '20 Years',
                'min_salary' => 3000,
                'max_salary' => 4500,
            ],
            [
                'name' => 'Jack Freedish',
                'email' => 'freedish@gmail.com',
                'password' => bcrypt('freedish'),
                'img' => '01_copy.jpg',
                'cover' => '1.jpg',
                'bio' => 'QA engineer committed to delivering high-quality software by designing and implementing comprehensive test plans. Skilled in automated testing and continuous integration.',
                'position' => 'System Audit',
                'birthday' => '1999-04-03',
                'age' => 25,
                'phone' => '09249353956',
                'country' => 'United States',
                'city' => 'New York',
                'skills' => '["6","19","12","15","10","18"]',
                'preferred_category' => 8,
                'experience' => '5 Years',
                'min_salary' => 900,
                'max_salary' => 1400,
            ],
            [
                'name' => 'Tote Kyi',
                'email' => 'totekyi@gmail.com',
                'password' => bcrypt('totekyi'),
                'img' => '02_copy.jpg',
                'cover' => '1.jpg',
                'bio' => 'Mobile app developer specializing in iOS and Android platforms. Proficient in both native and cross-platform development, creating seamless and responsive mobile applications.',
                'position' => 'Mobile Developer',
                'birthday' => '1997-04-30',
                'age' => 27,
                'phone' => '09943985243',
                'country' => 'Myanmar',
                'city' => 'Yangon',
                'skills' => '["10","16","13","14","10","12"]',
                'preferred_category' => 1,
                'experience' => '8 Years',
                'min_salary' => 2000,
                'max_salary' => 3000,
            ],
            [
                'name' => 'Oda Miyasaki',
                'email' => 'odamiyasaki@gmail.com',
                'password' => bcrypt('odamiyasaki'),
                'img' => '03.jpg',
                'cover' => '2.jpg',
                'bio' => 'Customer-focused IT support specialist with excellent communication skills and a knack for problem-solving. Experienced in providing technical assistance and resolving user issues.',
                'position' => 'IT Support',
                'birthday' => '2002-07-21',
                'age' => 22,
                'phone' => '09943985243',
                'country' => 'Japan',
                'city' => 'Nagoya',
                'skills' => '["6","12","4","17","18","13"]',
                'preferred_category' => 9,
                'experience' => '3 Years',
                'min_salary' => 700,
                'max_salary' => 1200,
            ],
        ];

        foreach ($usersData as $usersData) {
            $user = User::create([
                'name' => $usersData['name'],
                'email' => $usersData['email'],
                'password' => $usersData['password'],
                'img' => $usersData['img'],
                'cover' => $usersData['cover'],
                'bio' => $usersData['bio'],
                'position' => $usersData['position'],
                'birthday' => $usersData['birthday'],
                'age' => $usersData['age'],
                'phone' => $usersData['phone'],
                'country' => $usersData['country'],
                'city' => $usersData['city'],
                'skills' => $usersData['skills'],
                'preferred_category' => $usersData['preferred_category'],
                'experience' => $usersData['experience'],
                'min_salary' => $usersData['min_salary'],
                'max_salary' => $usersData['max_salary'],
            ]);

            $user->assignRole('candidate');
        }
    }
}
